name: 'Fetch open PRs'
description:
  'Fetches open PRs from repository and outputs them for following actions'
author: 'Jari Voutilainen'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'Repository from the pull requests are fetched'
    required: true
  ignored_users:
    description:
      'List of usernames which are ignored from the outputted PR list'
    required: false

# Define your outputs here.
outputs:
  PRs:
    description: 'List of open PRs in given format'

runs:
  using: node20
  main: dist/index.js
