name: 'Fetch open PRs'
description:
  'Fetches open PRs from repository and outputs them for following actions'
author: 'Jari Voutilainen'

inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'Repository from the pull requests are fetched'
    required: true
  ignored_users:
    description:
      'List of usernames which are ignored from the outputted PR list'
    required: false
  format:
    description: 'Format to use in output'
    required: false
    default: 'json'

outputs:
  PRs:
    description: 'List of open PRs in given format'

runs:
  using: node20
  main: dist/index.js
